### ISSUE TITLE
Burn in control errors when running

### ISSUE THREAD

**Issue by bflaggs** [umd-lhcb/NeoBurnIn#3] opened 2020-01-23 19:02 UTC
When following the steps outlined [here](https://github.com/umd-lhcb/lab-notes/wiki/RPi-set-up-and-burn-in-control#set-up-burn-in-system) in order to run the burn-in control code, the code will error. After opening three panels with `tmux` and running the commands then the third command, `./CtrlClient.py --config-file ./measurements/test_temp_ctrl_client.yml`, will error. Both the `./DataServer.py` and `./CtrlServer.py` commands run without issue.

The output in the `./CtrlClient.py` log file (`~/measurements/test_temp_ctrl_client.log`) is as follows...

```
Task exception was never retrieved
future: <Task finished coro=<CtrlClient.send() done, defined at /home/lhcb/src/NeoBurnIn/NeoBurnIn/io/client.py:151> exception=AttributeError("'DataPassthru' object has no attribute 'decode'")>

Traceback (most recent call last):
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/io/client.py", line 157, in send
if match(data):
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/functional.py", line 30, in combined
result = [f(data) for f in functors]
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/functional.py", line 30, in <listcomp>
result = [f(data) for f in functors]
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/functional.py", line 38, in <lambda>
return [lambda x, f=f, arg=arg: globals()[f](x, arg)
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/functional.py", line 17, in valueGt
return data.value > thresh
TypeError: '>' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/lhcb/src/NeoBurnIn/NeoBurnIn/io/client.py", line 171, in send
err.__class__.__name__, data.decode('utf8')
AttributeError: 'DataPassthru' object has no attribute 'decode'
```

I have attempted to find where exactly the problem is occurring although this is hard for myself due to the advanced level of the code. I believe it is something wrong with the encoding/decoding of `data` or with the relationship of `data` and `DataPassthru`. It is possible that data is being saved solely as a string making it have no instance of `data.value` meaning a call to `data.value` would result in `None` which has a type of `NoneType`. Although I am not sure how I would fix this issue while keeping the intended functionality of the original code. @yipengsun I believe that this may need to be solved with your expertise as you were the author of the code.

**Comment by yipengsun** [comment] 2020-01-24 07:38
That is because sometimes, the thermistor would give erroneous reading of 85.0. We have a workaround for that: As long as we don't read 85.0 for 3 consecutive times, the 85.0 will be ignored; instead, a `None` is returned. 

I think the client should run without problems, even if there's that exception that makes a single readout non-processable. If that is not the case, please let me know.

**Comment by yipengsun** [comment] 2020-01-24 07:42
Actually, this should already have been fixed. Take a look here:
https://github.com/umd-lhcb/NeoBurnIn/blob/a1aaf09fb4dd90154b01b58cd33dc9ea1e7c83c0/NeoBurnIn/DataSource/Therm.py#L21-L26

**Comment by yipengsun** [comment] 2020-01-24 07:42
@bflaggs try to do a `git pull` and see if there's any update. If not, I need to take a closer look.

**Comment by bflaggs** [comment] 2020-01-24 15:16
@yipengsun there was a single commit that was not updated on the pi. I pulled the repo on the pi to update it but I still am getting the same error. I made sure to update all software on the pi also just in case although the same error occurred.

**Comment by Derek-Colby** [comment] 2020-01-24 17:33
I think I fixed it. Changing line 25 of Therm.py to `if therm.value is not None` makes it work, since therm is the whole return statement with date and displayname here, not just the actual temperature.

**Comment by yipengsun** [comment] 2020-01-25 10:55
@Derek-Colby can you push your changes to `rpi.burnin` (I suppose `Therm.py` is part of the `rpi.burnin` package)?

It's curious that the line:
```python
if therm.value is not None:
    # push the data into the queue
```
fixes the problem, because I think that is equivalent to what I did.

**Comment by yipengsun** [comment] 2020-01-25 10:56
@bflaggs also, when you see that exception, did the `CtrlClient.py` crash? Or is it still running? Because I think these script should be tolerant enough that a single misformed message won't crash the whole program.

**Comment by yipengsun** [comment] 2020-01-25 11:23
Are you using the rpi's with NixOS, or maybe are you running the code in a Raspbian? I'm getting increasingly confused, because I don't think you have pushed the fix to `rpi.burnin`. In NixOS, I don't see a way to use your local Python package easily.

**Comment by yipengsun** [comment] 2020-01-27 03:49
@bflaggs @Derek-Colby I think I also find an additional bug that makes exception handling moot. Please try the latest `master` branch. This should work without @Derek-Colby's patch.

Now the expected behavior is: Sometimes due to the unreliability of the thermistor, a `None` value is spit out. The client will still treat this as an exception but will not crash. The incident will be logged but the client should be able to continue.

**Comment by bflaggs** [comment] 2020-01-27 18:18
@yipengsun Yes, when running the programs **only** `CtrlClient.py` crashed. The other two seemed to run fine although I did not thoroughly check their output `.log` files for incorrect information.

Later today I plan on downloading the new `master` branch and then attempting to run everything again. Once I do that I'll be sure to update you with its status.

**Comment by yipengsun** [comment] 2020-01-28 14:43
Also, are you still using NixOS?

**Comment by bflaggs** [comment] 2020-01-28 17:53
I believe that I am still using NixOS as long as that is still the OS on the pi.

I was not able to check if the updates are working as I could not connect to the internet on the pi. I was attempting to share the internet from my laptop to the pi but it did not work. It's interesting though because it **did** work last week. I'm going to try again tomorrow and hopefully it will connect.

**Comment by bflaggs** [comment] 2020-01-29 15:12
@yipengsun I restored all versions of the files on the raspberry pi to their original versions and then pulled your latest updates from GitHub. So I ran the scripts **with** your updates but **without** Derek's updates. Everything now runs without errors when I run your updated versions of the scripts.

For your second question, yes we are still using NixOS on the raspberry pi.

**Comment by bflaggs** [comment] 2020-01-29 17:10
I have found that the code when run will turn the switch on the relay control `ON` and `OFF` provided the correct requirements are met **however**, the output log file `CtrlServer.py` will only log that the relay control is being turned `ON` even if it is actually being turned `OFF`.

I have looked into where this error is occurring and I believe that it is occurring on line 219 of the file `NeoBurnin/io/server.py` as on this line it only logs that the relay control is turning `ON`. I will attempt to fix this problem now although I only have a few minutes so I may need to continue trying to fix this problem tomorrow afternoon.

**Comment by yipengsun** [comment] 2020-01-30 05:27
Good! As a side note, if you want to test out a remote fix without messing up your local code, you can just do the following thing:
```
git clone <url_to_this_repo> <local_folder_name>
cd <local_folder_name>
nix-shell
pip install -U -r requirements.txt
```
After entering the `nix-shell` and installing additional Python packages, you can follow the old instruction to test out the new setup.

**Comment by bflaggs** [comment] 2020-01-31 13:53
The code now runs without error and will correctly log when the relay control is turned `on` and when it is turned `off`. This error of incorrect logging was occurring at line 219 of the file `NeoBurnIn/io/server.py`. The fix was only one line of code so I will push my updates to `master` branch once I can get internet connection on the pi setup.

**Closed as completed** 2020-02-04 06:34 UTC
Labels: bug
