### ISSUE TITLE
Add MARATON current data to logging

### ISSUE THREAD

**Issue by CoffeeIntoScience** [umd-lhcb/NeoBurnIn#4] opened 2020-01-28 17:54 UTC
Since the current output from the Maraton is available to us in principle it would be very powerful to log this. It could be only every 10 or 15 minutes. We'd be looking for a sudden step of ~2A which would indicate a channel failure.

I will get my code to pull this info cleaned a bit and put up ASAP

**Comment by yipengsun** [comment] 2020-02-07 14:53
@bflaggs @ZishuoYang @CoffeeIntoScience This is also ready to be tested. Once you finish configuring the network in the basement lab, you can try the latest `master` branch.

A sample configuration file is located at `measurements/test_temp_ctrl_client.yml`.

**Comment by CoffeeIntoScience** [comment] 2020-02-07 15:12
very rad! hopefully we will have something in the basement on a permanent basis soon

The plan will be to have the "production" pi be accessible via SSH *from inside the university network*. So you will need to either via the university's VPN or come in via another computer exposed to the outside. If some other accommodation is needed we can discuss.

**Comment by yipengsun** [comment] 2020-02-07 15:16
I can ssh into the computer sitting on top of my desk. That is a good jumper. The problem is: ssh is not reliable here (frequently interrupted by THE firewall).

I plan to investigate on a more robust proxy.

**Comment by yipengsun** [comment] 2020-02-07 15:17
BTW, the first time you launch the script, it will probably take a long time: 
```python
from pysnmp.hlapi import *
```
is actually very slow initially.

**Comment by yipengsun** [comment] 2020-02-28 06:40
This seems to be working. I've made very small improvements and we should be able to close this after Ben tests the improved code.

**Closed as completed** 2020-06-17 11:11 UTC
Labels: enhancement
